x = 17
y = 3.14
z = "The Walrus and the Carpenter"
z1 = "30"
z2 = '40'
vowel = ['a','e','i','o','u']
num = ['1','2','3','3.14']
phrases = ["Twas brilling, and the slithy toves","Did gyre and gimble:"]
r = True
s = False
